apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: acctdev
spec:
  image: registry.crunchydata.com/crunchydata/crunchy-postgres:ubi8-13.4-1
  imagePullSecrets:
  - name: crunchyreg
  openshift: true
  port: 5432
  postgresVersion: 13
  instances:
    - name: 'instance1'
      replicas: 2
      resources:
        limits:
          cpu: 1.0
          memory: 2Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi
  backups:
    pgbackrest:
      image: registry.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.35-0
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * 7"
          incremental: "0 1 * * 1-6"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi

  monitoring:
    pgmonitor:
      exporter:
        image: registry.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.5-0

#  patroni:
#    dynamicConfiguration:
#      postgresql:
#        parameters:
          #shared_buffers: 256MB
          #work_mem: 2MB

# tag for upgrade ubi8-13.5-0
